title: Augustinianum
author: Augustinianum sectie Natuurkunde
execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  favicon : "figures/favicon.ico"
  baseurl :  "https://augustinianum.nl/" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      logo:
        image_light: figures/AUG-logo.png # 
        image_dark: figures/AUG-logo.png # niet nodig om te inverter
      repository_url: "https://github.com/AUG-natuurkunde/aug-template" #uitgeschakeld, dus maakt niet uit
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: false
      use_repository_button: false
      use_issues_button : false
      launch_buttons:
        thebe: true
    html_show_copyright: false
    html_last_updated_fmt: '%-d, %B, %Y'
    html_static_path: ["figures"] # add folders that contain files that need to be included, such as the location of the logo(s)
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
  extra_extensions:
    - sphinx.ext.imgconverter
    - jupyterbook_patches
    - download_link_replacer
    - sphinx.ext.extlinks
    - sphinx_image_inverter
    - sphinx_exercise_nl

bibtex_bibfiles: 
  - references.bib
